spring.application.name=cafeiq

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cafeiq
spring.datasource.username=charitha
spring.datasource.password=

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
gemini.api.key=${GEMINI_API_KEY}